echo "create widget_template ..."
if [ "1" ] ; then 
echo 'CLASS QWidget TestWidget'
echo ''
echo 'D QLabel ori_x_label "ori x :"'
echo 'D QLineEdit ori_x_edit "50.00"'
echo ''
echo 'D QLabel ori_y_label "ori y :"'
echo 'D QLineEdit ori_y_edit "50.00"'
echo ''
echo 'D QLabel ori_z_label "ori z :"'
echo 'D QLineEdit ori_z_edit "0.00"'
echo ''
echo 'D QLabel radius_label "radius :"'
echo 'D QLineEdit radius_edit "5"'
echo ''
echo 'D QLabel step_length_label "step length :"'
echo 'D QLineEdit step_length_edit "20"'
echo ''
echo 'D QLabel nrows_label "num rows :"'
echo 'D QSpinBox nrows_spin | setValue(5)'
echo ''
echo 'D QLabel ncols_label "num cols :"'
echo 'D QSpinBox ncols_spin | setValue(3)'
echo ''
echo 'D QLabel nlayers_label "num layers :"'
echo 'D QSpinBox nlayers_spin | setValue(1)'
echo ''
echo 'D QPushButton create_button "create"'
echo 'D QPushButton clear_button "clear"'
echo ''
echo 'D QGridLayout gridLayout'
echo 'L 0 0 ori_x_label'
echo 'L 0 1 ori_x_edit'
echo 'L 1 0 ori_y_label'
echo 'L 1 1 ori_y_edit'
echo 'L 2 0 ori_z_label'
echo 'L 2 1 ori_z_edit'
echo 'L 3 0 radius_label'
echo 'L 3 1 radius_edit'
echo 'L 4 0 step_length_label'
echo 'L 4 1 step_length_edit'
echo 'L 5 0 nrows_label'
echo 'L 5 1 nrows_spin'
echo 'L 6 0 ncols_label'
echo 'L 6 1 ncols_spin'
echo 'L 7 0 nlayers_label'
echo 'L 7 1 nlayers_spin'
echo 'L 8 0 create_button 1 2'
echo 'L 9 0 clear_button 1 2'
echo ''
echo 'C ori_x_edit textChanged(const QString &) this update()'
echo 'C ori_y_edit textChanged(const QString &) this update()'
echo 'C ori_z_edit textChanged(const QString &) this update()'
echo 'C radius_edit textChanged(const QString &) this update()'
echo 'C step_length_edit textChanged(const QString &) this update()'
echo 'C nrows_spin valueChanged(int) this update()'
echo 'C ncols_spin valueChanged(int) this update()'
echo 'C nlayers_spin valueChanged(int) this update()'
echo ''
echo 'R this | setLayout(gridLayout)'
echo 'R this | setWindowTitle("Best Spanning Tree")'
echo ''
echo 'U double ori_x | ori_x_edit->text().toDouble()'
echo 'U double ori_y | ori_y_edit->text().toDouble()'
echo 'U double ori_z | ori_z_edit->text().toDouble()'
echo 'U double radius | radius_edit->text().toDouble()'
echo 'U double step_length | step_length_edit->text().toDouble()'
echo 'U int nrows | nrows_spin->text().toInt()'
echo 'U int ncols | ncols_spin->text().toInt()'
echo 'U int nlayers | nlayers_spin->text().toInt()'
echo ''
fi > widget_template

