echo "create split.cpp ..."
if [ "1" ] ; then 
echo '#include <stdlib.h>'
echo '#include <string.h>'
echo ''
echo 'int split(const char *paras, char ** &args)'
echo '{'
echo '	int argc = 0;'
echo '	int len = strlen(paras);'
echo '	int posb[200];'
echo '	char * myparas = new char[len];'
echo '	strcpy(myparas, paras);'
echo '	for(int i = 0; i < len; i++)'
echo '	{'
echo '		if(i==0 && myparas[i] != '"'"' '"'"' && myparas[i] != '"'"'\t'"'"')'
echo '		{'
echo '			posb[argc++]=i;'
echo '		}'
echo '		else if((myparas[i-1] == '"'"' '"'"' || myparas[i-1] == '"'"'\t'"'"') && '
echo '				(myparas[i] != '"'"' '"'"' && myparas[i] != '"'"'\t'"'"'))'
echo '		{'
echo '			posb[argc++] = i;'
echo '		}'
echo '	}'
echo ''
echo '	args = new char*[argc];'
echo '	for(int i = 0; i < argc; i++)'
echo '	{'
echo '		args[i] = myparas + posb[i];'
echo '	}'
echo ''
echo '	for(int i = 0; i < len; i++)'
echo '	{'
echo '		if(myparas[i]=='"'"' '"'"' || myparas[i]=='"'"'\t'"'"')myparas[i]='"'"'\0'"'"';'
echo '	}'
echo '	return argc;'
echo '}'
echo ''
echo '#include <iostream>'
echo 'using namespace std;'
echo 'int main()'
echo '{'
echo '	char paras[]="-i input.tif -o output.tif -s -N 20 -p 30x0+100x30 -k left -S";'
echo '	char ** args;'
echo '	int argc = split(paras, args);'
echo '	cout<<"argc = "<<argc<<endl;'
echo '	for(int i = 0; i< argc; i++) cout<<i<<": "<<args[i]<<endl;'
echo '	return 0;'
echo '}'
fi > split.cpp

