echo "create v3d_imgio.cpp ..."
if [ "1" ] ; then 
echo '/* convert.cpp'
echo ' * 2010-02-08: the program is created by Hang Xiao'
echo ' */'
echo ''
echo '// '
echo ''
echo '#ifndef __CONVERT_SRC_CPP__'
echo '#define __CONVERT_SRC_CPP__'
echo ''
echo '#include <iostream>'
echo '#include "stackutil.h"'
echo ''
echo 'using namespace std;'
echo ''
echo 'int main(int argc, char* argv[])'
echo '{'
echo '	if(argc != 3)'
echo '	{'
echo '		cout<<"Usage : v3d_convert input_img output_img"<<endl;'
echo '		cout<<"Support raw, tiff image format"<<endl;'
echo '		return 0;'
echo '	}'
echo '	unsigned char * data1d=NULL;'
echo '	V3DLONG *sz=NULL;'
echo '	int datatype;'
echo '	loadImage(argv[1], data1d, sz, datatype);'
echo '	saveImage(argv[2], data1d,sz, datatype);'
echo '}'
echo ''
echo '#endif'
echo ''
fi > v3d_imgio.cpp

echo "create Makefile ..."
if [ "1" ] ; then 
echo 'CC = g++ -g'
echo 'CC_FLAGS += -I../../../v3d_main/basic_c_fun -I../../../v3d_main/common_lib/include'
echo 'LIBS +=  -L../../../v3d_main/common_lib/lib -lv3dtiff'
echo ''
echo 'COMMON_OBJS = basic_memory.o stackutil.o mg_image_lib.o mg_utilities.o'
echo 'SHARED_FUNC_DIR = ../../../v3d_main/basic_c_fun/'
echo ''
echo 'v3d_imgio: v3d_imgio.o ${COMMON_OBJS}'
echo '	${CC}  ${CC_FLAGS} v3d_imgio.o ${COMMON_OBJS} ${LIBS} -o v3d_imgio'
echo 'v3d_imgio.o : v3d_imgio.cpp'
echo '	${CC} ${CC_FLAGS} -c v3d_imgio.cpp'
echo 'basic_memory.o : ${SHARED_FUNC_DIR}basic_memory.h ${SHARED_FUNC_DIR}basic_memory.cpp'
echo '	${CC} ${CC_FLAGS} -c ${SHARED_FUNC_DIR}basic_memory.cpp'
echo 'stackutil.o : ${SHARED_FUNC_DIR}stackutil.h ${SHARED_FUNC_DIR}stackutil.cpp'
echo '	${CC} ${CC_FLAGS} -c ${SHARED_FUNC_DIR}stackutil.cpp'
echo 'mg_image_lib.o : ${SHARED_FUNC_DIR}mg_image_lib.h ${SHARED_FUNC_DIR}mg_image_lib.cpp'
echo '	${CC} ${CC_FLAGS} -c ${SHARED_FUNC_DIR}mg_image_lib.cpp'
echo 'mg_utilities.o : ${SHARED_FUNC_DIR}mg_utilities.h ${SHARED_FUNC_DIR}mg_utilities.cpp'
echo '	${CC} ${CC_FLAGS} -c ${SHARED_FUNC_DIR}mg_utilities.cpp'
echo 'clean:'
echo '	rm *.o'
fi > Makefile
echo ""
echo "Please set v3d_main path in Makefile correctly."
