echo "create main.c ..."
if [ "1" ] ; then 
echo '#include <stdlib.h>'
echo '//#include <GL/glut.h>'
echo '#include <OpenGL/gl.h>'
echo '#include <OpenGL/glu.h>'
echo '#include <GLUT/glut.h>'
echo 'void background(void)'
echo '{'
echo '	glClearColor(0.0,0.0,0.0,0.0);'
echo '}'
echo ''
echo 'void myDisplay(void)'
echo '{'
echo '	glClear(GL_COLOR_BUFFER_BIT);'
echo '	glBegin(GL_TRIANGLES);'
echo '	glShadeModel(GL_SMOOTH);'
echo '	glColor3f(1.0,0.0,0.0);'
echo '	glVertex2f(-1.0,-1.0);'
echo '	glColor3f(0.0,1.0,0.0);'
echo '	glVertex2f(0.0,-1.0);'
echo '	glColor3f(0.0,0.0,1.0);'
echo '	glVertex2f(-0.5,1.0);'
echo '	glEnd();'
echo '	glFlush();'
echo '}'
echo ''
echo 'void myReshape(GLsizei w, GLsizei h)'
echo '{'
echo '	glViewport(0,0,w,h);'
echo '	glMatrixMode(GL_PROJECTION);'
echo '	glLoadIdentity();'
echo ''
echo '	if(w<=h)'
echo '		gluOrtho2D(-1.0,1.5,-1.5,1.5*(GLfloat)h/(GLfloat)w);'
echo '	else'
echo '		gluOrtho2D(-1.0,1.5*(GLfloat)w/(GLfloat)h,-1.5,1.5);'
echo '	glMatrixMode(GL_MODELVIEW);'
echo '}'
echo ''
echo 'int main(int argc, char** argv)'
echo '{'
echo '	glutInit(&argc,argv);'
echo '	glutInitDisplayMode(GLUT_SINGLE|GLUT_RGB);'
echo '	glutInitWindowSize(400,400);'
echo '	glutInitWindowPosition(200,200);'
echo '	glutCreateWindow("Triangle");'
echo '	background();'
echo '	glutReshapeFunc(myReshape);'
echo '	glutDisplayFunc(myDisplay);'
echo '	glutMainLoop();'
echo '	return(0);'
echo '}'
echo ''
fi > main.c

echo "create makefile ..."
if [ "1" ] ; then 
echo 'all: main.c'
echo '	gcc -framework GLUT -framework OpenGL  main.c'
fi > makefile

